# frozen_string_literal: true

source 'https://rubygems.org'

gem "sinatra", "~> 3.0"

gem "puma", "~> 6.3"

gem "rackup", "~> 1.0"

gem "firebase", "~> 0.2.8"

gem "dotenv", "~> 2.8"

group :development do
    gem "rerun", "~> 0.14.0"
end
