// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/areas.tsx";
import * as $3 from "./routes/bosques.tsx";
import * as $4 from "./routes/ciudad.tsx";
import * as $5 from "./routes/resenia/[id].tsx";
import * as $6 from "./routes/resenia/[id]/create.tsx";
import * as $$0 from "./islands/ReseniaButton.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/areas.tsx": $2,
    "./routes/bosques.tsx": $3,
    "./routes/ciudad.tsx": $4,
    "./routes/resenia/[id].tsx": $5,
    "./routes/resenia/[id]/create.tsx": $6,
  },
  islands: {
    "./islands/ReseniaButton.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
