// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[cat].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/resenia/[id].tsx";
import * as $5 from "./routes/resenia/[id]/create.tsx";
import * as $$0 from "./islands/BackButton.tsx";
import * as $$1 from "./islands/CardResenia.tsx";
import * as $$2 from "./islands/CatButton.tsx";
import * as $$3 from "./islands/ReseniaButton.tsx";
import * as $$4 from "./islands/ReseniaCreateButton.tsx";

const manifest = {
  routes: {
    "./routes/[cat].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/resenia/[id].tsx": $4,
    "./routes/resenia/[id]/create.tsx": $5,
  },
  islands: {
    "./islands/BackButton.tsx": $$0,
    "./islands/CardResenia.tsx": $$1,
    "./islands/CatButton.tsx": $$2,
    "./islands/ReseniaButton.tsx": $$3,
    "./islands/ReseniaCreateButton.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
